// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARVZXjzyGVOtkIjPRUxn2cBlizwi56abo',
    appId: '1:718249061465:web:e7441c4ae6cf34eec45548',
    messagingSenderId: '718249061465',
    projectId: 'cw08-66d47',
    authDomain: 'cw08-66d47.firebaseapp.com',
    storageBucket: 'cw08-66d47.firebasestorage.app',
    measurementId: 'G-CYKXSELPE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4A2xWRg3v8AWzyUTk4S61zgG4hE3SyMM',
    appId: '1:718249061465:android:407bf9b52b4b342ec45548',
    messagingSenderId: '718249061465',
    projectId: 'cw08-66d47',
    storageBucket: 'cw08-66d47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdvjpFN6LU6bl3ugX0cd2dW_F15VrmH8',
    appId: '1:718249061465:ios:9bf03dbf397a2e7ac45548',
    messagingSenderId: '718249061465',
    projectId: 'cw08-66d47',
    storageBucket: 'cw08-66d47.firebasestorage.app',
    iosBundleId: 'com.example.cw8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdvjpFN6LU6bl3ugX0cd2dW_F15VrmH8',
    appId: '1:718249061465:ios:9bf03dbf397a2e7ac45548',
    messagingSenderId: '718249061465',
    projectId: 'cw08-66d47',
    storageBucket: 'cw08-66d47.firebasestorage.app',
    iosBundleId: 'com.example.cw8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARVZXjzyGVOtkIjPRUxn2cBlizwi56abo',
    appId: '1:718249061465:web:918059a65dec3568c45548',
    messagingSenderId: '718249061465',
    projectId: 'cw08-66d47',
    authDomain: 'cw08-66d47.firebaseapp.com',
    storageBucket: 'cw08-66d47.firebasestorage.app',
    measurementId: 'G-TQ1Q0C8CG5',
  );
}
